### ISSUE TITLE
make the plot more condense

### ISSUE THREAD

**Issue by liuyifang** [zji90/TSCAN#3]
<img width="445" alt="screen shot 2017-11-29 at 9 42 26 pm" src="https://user-images.githubusercontent.com/520808/33377969-473344d4-d54e-11e7-97cf-9872b65bed4b.png">
Hi, whether there is a parameter to make the cells more closer to the cluster center? Thanks.

**Comment by zji90** [comment]
Do you mean you still want the cluster center to be in the same location but only make the cells stick closer to the center? Or you want to zoom out the plot (increasing the range of PC1 and PC2)?

**Comment by liuyifang** [comment]
I mean the previous one, the center is in the same location but only move the cells more closer to the center, so that the cell trajectory will be more clear (my own data have > 30k cells).

**Comment by zji90** [comment]
I don't think it is valid to arbitrarily move cells towards the cluster centers while fixing the cluster centers. This is data manipulation and is not a good practice. I think your problem is more a data visualization issue where you have too many dots to plot. I would suggest you either decrease the number of cells (for example, remove cells that have too few genes detected) and redo the whole analysis, or plot the dots with transparency by setting alpha values. Currently the singlegeneplot function in TSCAN does not have the transparency function. I can add the function if you feel necessary. Please let me know if you want that function to be added.

**Comment by liuyifang** [comment]
Thank you for your advice. I agree with you this is a visualization issue. I have already removed cells based on genes and UMIs. My goal is to use several pseudo-time analysis tools and get similar cell trajectory. TSCAN and Monocle's trajectory are pretty similar. But the cells' position in TSCAN are too broad. It is not consistent to use Monocle with original dots but use TSCAN with transparency. I prefer moving cells than adding transparency to the cells.
<img width="831" alt="screen shot 2017-11-29 at 10 57 09 pm" src="https://user-images.githubusercontent.com/520808/33381958-6b78422a-d55a-11e7-9ee3-d6f77576608a.png">
For example, monocle2's supplementary figure 13 has the `Gamma` and `Sigma` parameters to adjust the cells position, I hope you can point out if it is possible to adjust cell' position in TSCAN.  Thanks.

**Comment by zji90** [comment]
TSCAN simply uses a PCA to perform the dimension reduction and does not have complicated statistical models built in to model the data points. So I would say the answer is no, TSCAN does not have the option to adjust cell positions. Another possibility is to adjust your criteria of filtering genes and doing gene clustering to see whether the PCA results change. Try different cutoffs to filter genes and different cluster numbers before PCA.

**Comment by liuyifang** [comment]
OK, I will try the different gene clusters to see if the PCA results will change. Thanks.
