### ISSUE TITLE
pseudotime calculation

### ISSUE THREAD

**Issue by galicae** [zji90/TSCAN#4]
I am trying to assign pseudotime to all cells in a dataset. TSCAN calculates pseudotime per ordered path. Is it possible to obtain a global pseudotime for the whole structure given a starting cell/starting cluster? How would I do this?

There is a [similar question](https://support.bioconductor.org/p/96967/) on the Bioconductor support site, but no answer.

**Comment by zji90** [comment]
Hi,
If you have a structure with multiple branches, currently it is not possible to get a global pseudotime. This is because the pseudotime from different branches are not directly comparable to each other.
If you really need to get a single path (thus global pseudotime) for all the cells you have, you can adjust the number of cell clusters in exprmclust step until only one path exists. You can also supply with your own dimension reduction/cell clustering results in exprmclust function to overwrite the default one. In the extreme case where you only have two clusters, you will definitely going to get only one path.
